#kubectl create secret generic mesto-backend-secret --from-env-file=.env --namespace kybikn
apiVersion: v1
kind: Secret
metadata:
  name: mesto-backend-secret
  namespace: kybikn
data:
  JWT_SECRET: >-
    ZDUyNzJkNTUyODZiYWJiYWI3
  MONGO_URL_PROD: >-
    bW9uZ29kYjovL3Jvb3Rsb2dpbjpyb290c
  NODE_ENV: c
  PORT: M
type: Opaque
