apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: kybikn
spec:
  # ClusterIP — самый простой тип сервиса, который
  # позволяет подам связываться друг с другом в рамках
  # кластера, но абсолютно никак не виден снаружи:
  type: ClusterIP
  clusterIP: None
  selector:
    app: mongodb-app
